version: '3.9'

networks:
  vending_network:

services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    container_name: '${APP_NAME}-server'
    ports:
      - '${APP_PORT}:80'
    working_dir: /var/www/html
    environment:
      - 'DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@database:3306/${MYSQL_DB}?serverVersion=8'
    volumes:
      - ./skeleton:/var/www/html
      - ./docker/server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./docker/server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
    depends_on:
      database:
        condition: service_healthy
    networks:
      - vending_network

###> doctrine/doctrine-bundle ###
  database:
    image: mysql:8.0
    container_name: '${APP_NAME}-db'
    restart: always
    environment:
      MYSQL_DATABASE: '${MYSQL_DB}'
      # You should definitely change the password in production
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_ROOT_PASS}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_PASS}'
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3307:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    volumes:
      - ./docker/db/data:/var/lib/mysql:rw
      - ./docker/db/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u root --password=$$MYSQL_ROOT_PASSWORD
      interval: 5s
      retries: 5
    networks:
      - vending_network
###< doctrine/doctrine-bundle ###

  db_admin:
    image: phpmyadmin/phpmyadmin:5
    container_name: '${APP_NAME}-db-admin'
    ports:
      - '${APP_DB_ADMIN_PORT}:80'
    environment:
      PMA_HOST: db_server
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - db_admin_data:/var/www/html
    networks:
      - vending_network

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###
  db_admin_data:
